# Example Wrangler Configuration for Odissey Backend
# Copy this file to wrangler.toml and fill in your values

name = "odissey-backend"
compatibility_date = "2024-01-15"
main = "src/index.ts"

# Database binding
[[d1_databases]]
binding = "DB"
database_name = "odissey-db"
database_id = "your-d1-database-id-here"

# Environment variables for development
[env.development.vars]
# Required: Get your HuggingFace API key from https://huggingface.co/settings/tokens
HUGGINGFACE_API_KEY = "hf_your_huggingface_api_key_here"

# Optional: Add these for additional AI provider support
# OPENAI_API_KEY = "sk-your_openai_api_key_here"
# GEMINI_API_KEY = "your_gemini_api_key_here"

# Environment variables for production
[env.production.vars]
HUGGINGFACE_API_KEY = "hf_your_production_huggingface_api_key_here"
# OPENAI_API_KEY = "sk-your_production_openai_api_key_here"
# GEMINI_API_KEY = "your_production_gemini_api_key_here"

# CORS settings are handled in code, but you can customize here if needed
[env.development]
name = "odissey-backend-dev"

[env.production]
name = "odissey-backend-prod" 